### ISSUE TITLE
Doesn't work on heroku

### ISSUE THREAD

**Issue by kovak7** [titaniumnetwork-dev/UV-OLD#1]
Doesn't work on heroku

![image](https://user-images.githubusercontent.com/97852069/155660552-06c7f25f-1bc6-4203-8446-3d99119ede9a.png)

**Comment by nevr13** [comment]
Now it does. Just go to https://github.com/titaniumnetwork-dev/ultraviolet-web-app, and hit Deploy To Heroku.

**Comment by Sylveondev** [comment]
Doesn't work on heroku still because it violates some policy

**Comment by pbkx** [comment]
Heroku actively blocks all proxy services

Bastards

**Comment by kovak7** [comment]
> Heroku actively blocks all proxy services
> 
> Bastards

They just want to prevent you from stealing other people's work, so you must fork it, rename the project, and rename "Ultraviolet" to something else in the app.json file.

**Comment by shirt-dev** [comment]
> > Heroku actively blocks all proxy services
> > Bastards
> 
> They just want to prevent you from stealing other people's work, so you must fork it, rename the project, and rename "Ultraviolet" to something else in the app.json file.

Incorrect, heroku bans proxies due to bandwidth consumption.
