### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by EmulatorOS** [titaniumnetwork-dev/UV-OLD#13]
Is there a way to run this on github pages?

**Comment by 3kh0** [comment]
No

**Comment by EmulatorOS** [comment]
Then whats a good deployment site that can run nodejs

**Comment by EmulatorOS** [comment]
And free

**Comment by 3kh0** [comment]
I suggest using replit, they offer this kind of service and it is for free although you can upgrade to the hacker plan if you need more. Regardless, the free plan is just fine for hosting a proxy, the limits are very generous.
