### ISSUE TITLE
Blocked in my network

### ISSUE THREAD

**Issue by Titanic-byte** [titaniumnetwork-dev/UV-OLD#18]
The ultraviolet website is blocked in my school maybe you could make a different URL for it pls that would be very helpful thank you  😀

**Comment by SupremeRubisco** [comment]
> The ultraviolet website is blocked in my school maybe you could make a different URL for it pls that would be very helpful thank you 😀

Try running it on replit or Heroku

**Comment by shirt-dev** [comment]
out of scope
