### ISSUE TITLE
Heroku app not working

### ISSUE THREAD

**Issue by joseereal** [titaniumnetwork-dev/UV-OLD#19]
When I try making a new link it shows this
![Screenshot 2022-04-27 9 44 22 AM](https://user-images.githubusercontent.com/104520252/165576792-df6d7b2e-c9f4-4901-bb81-cb0fa16b3bfe.png)

**Comment by SupremeRubisco** [comment]
Try forking it

**Comment by ghost** [comment]
> Try forking it

how do i fork it? like step by step, im dumb. I have github and heroku account.

**Comment by ghost** [comment]
> > Try forking it
> 
> how do i fork it? like step by step, im dumb. I have github and heroku account.

nvm, im dumb, it still shows same thing tho.

**Comment by SupremeRubisco** [comment]
> > Try forking it
> 
> how do i fork it? like step by step, im dumb. I have github and heroku account.

I did everything for you, just go to this heroku link: https://heroku.com/deploy/?template=https://github.com/supremerubisco/Ultraviolet-Node
Should Work

Hope this helps,
SupremeRubisco

**Comment by VitamimFUCK** [comment]
> 

When I Open the app is gives me this 
¨This ultravioletschoolproxy.herokuapp.com page can’t be found
No webpage was found for the web address: https://ultravioletschoolproxy.herokuapp.com/¨

**Comment by imranhwafa** [comment]
I had this problem I bypassed by getting it running on my local machine and getting that code to GitHub where then I upload it to heroku I would give you mine  but I changed my ./static and its style sheet I will revert those changes in a fork and give you a link

**Comment by shirt-dev** [comment]
Heroku is not supported
