### ISSUE TITLE
this page cant be found error

### ISSUE THREAD

**Issue by spityou2** [titaniumnetwork-dev/UV-OLD#20]
## Expected Behavior
it should connect me to the proxy's website
## Current Behavior

says this page cant be found 
## Possible Solution

dont know
## Steps to Reproduce

1.copy this pages github site link and make a copy
2. deploy that new github repository on heroku
3. tap view site
4. site says "this page cant be found
5. here is my heroku site for ultraviolet = https://test1n2.herokuapp.com/

## Context (Environment)

proxy for my school computer

**Comment by HunterBoy344** [comment]
Try deploying to Replit instead? Hasn't failed for me thus far...

You can also just search Replit for existing instances of Ultraviolet. I've been using [this one](https://ultraviolet.joshuarice3.repl.co/).

**Comment by imranhwafa** [comment]
The deployment to heroku is bugged I will give a different url for it to work

**Comment by shirt-dev** [comment]
Heroku is not supported
