### ISSUE TITLE
iRangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

### ISSUE THREAD

**Issue by ghost** [titaniumnetwork-dev/UV-OLD#5]
This error occurs when I try to use Ultra Violet (on some sites) behind a Nginx Proxy, this does not happen when I access it directly.
![image](https://user-images.githubusercontent.com/102445067/160262392-fba19683-5dfe-4d87-b082-af59fdc4034e.png)

**Comment by caracal-js** [comment]
Ah this is a Nginx config issue. I'll post the configurations Incognito uses right now.

**Comment by caracal-js** [comment]
Nginx configuration is now on README.md, try using the configuration.

**Comment by ghost** [comment]
> Nginx configuration is now on README.md, try using the configuration.

Thanks!

**Comment by ghost** [comment]
Never mind it is still doing the same thing, please help.

**Comment by ghost** [comment]
Oops, I put 127.0.0.1 instead of localhost. It works now.
