### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by ImNotAlive1** [titaniumnetwork-dev/UV-OLD#7]
This thing is incredibly slow. Im currently on a school chromebook, which is one of the reasons but it takes like 5 minutes just to load the website. Loading games is even worse. Just wanted to let you guys know that, great website for unblocking stuff and all that.

**Comment by 3kh0** [comment]
Uhhh, for me the proxy is pretty fast, so either it is your network being slow or your school Chromebook being slow.

**Comment by hchy-guy** [comment]
Im on school chromebook and its a lot faster

**Comment by SupremeRubisco** [comment]
No, ultraviolet is quite slow on replit.
