### ISSUE TITLE
Errors when running replit

### ISSUE THREAD

**Issue by Sanityfrog502** [titaniumnetwork-dev/UV-OLD#8]
When i run on replit (with following what you guys said) I get a lot of errors it says this can I please get help:

--> npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/tomphttp/bare-server-node.git
npm ERR! 
npm ERR! ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-04-08T18_40_43_896Z-debug.log
exit status 1

Replit: Package operation failed.

**Comment by Sanityfrog502** [comment]
update i got it to work i think by doing "npm i cordova@latest" but when I go to the site and type in what I want to search and hit enter nothing happens I think it has something to do with the error I got above saying "npm ERR! Host key verification failed."

**Comment by shirt-dev** [comment]
We do not support repl.it, please follow the issue guidelines.
